# -*- coding: utf-8 -*-
"""
File Exchange With GEOPHIRES
=============================

Writes a production history to the files GEOPHIRES reads, so that a
superhot well can be used as a GEOPHIRES reservoir without changing a
single line of GEOPHIRES code:

    <name>_reservoir_temperature.csv
        Two-column 'time [yr], temperature [C]' profile, the format
        expected by the GEOPHIRES 'User-Provided Temperature Profile'
        reservoir model (Reservoir Model 5) through its
        'Reservoir Output File Name' parameter.

    <name>_geophires.txt
        A GEOPHIRES input deck fragment that selects that reservoir
        model, points at the profile file and carries the well and
        operating parameters derived from the superhot solution
        (flow rate, wellhead pressure, depth, gradient, ...).

    <name>_profile.json
        The complete client result: request, summary, notes, the
        GEOPHIRES parameter mapping and every timestep. This is the
        machine-readable output of the command-line client and is not
        read by GEOPHIRES itself.

GEOPHIRES input decks are line oriented, 'Parameter Name, value,
optional comment', with '#', '--' and '*' starting a comment line
(see geophires_x/GeoPHIRESUtils.read_input_file).

Author: superhot-wellbore GEOPHIRES client
"""

import json
import os

from .results import PROFILE_TEMPERATURES


# ====================================================================
# DECK LAYOUT
# ====================================================================

#: Order in which known parameters are written into the input deck,
#: grouped the way GEOPHIRES examples are laid out.
_PARAMETER_ORDER = (
    'Reservoir Model',
    'Reservoir Output File Name',
    'Plant Lifetime',
    'Time steps per year',
    'Reservoir Depth',
    'Maximum Temperature',
    'Surface Temperature',
    'Gradient 1',
    'Reservoir Hydrostatic Pressure',
    'Number of Production Wells',
    'Number of Injection Wells',
    'Production Well Diameter',
    'Production Flow Rate per Well',
    'Production Wellhead Pressure',
    'Ramey Production Wellbore Model',
    'Production Wellbore Temperature Drop',
)

#: Short explanations written as the third, comment field of each line
_PARAMETER_COMMENTS = {
    'Reservoir Model': 'user-provided temperature profile',
    'Reservoir Output File Name': 'written by the superhot client',
    'Reservoir Depth': 'km, feedzone depth of the superhot well',
    'Maximum Temperature': 'C, raised to admit the superhot reservoir',
    'Gradient 1': 'C/km, average to the feedzone',
    'Reservoir Hydrostatic Pressure': 'kPa, far-field reservoir pressure',
    'Production Flow Rate per Well': 'kg/s, from the coupled model',
    'Production Wellhead Pressure': 'kPa, from the coupled model',
    'Ramey Production Wellbore Model': 'the superhot wellbore model '
                                       'already applied heat loss',
    'Production Wellbore Temperature Drop': 'C, already applied',
}


def _format_value(value):
    """Render a parameter value the way GEOPHIRES parses it."""
    if isinstance(value, bool):
        return 'True' if value else 'False'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f'{value:.6g}'
    return str(value)


# ====================================================================
# PROFILE FILE
# ====================================================================

def write_temperature_profile(profile, path,
                              profile_temperature='wellhead'):
    """
    Write the GEOPHIRES 'Reservoir Output File Name' profile.

    Parameters
    ----------
    profile : ProductionProfile
        Result of SuperhotWellboreClient.solve_profile().
    path : str
        Destination file.
    profile_temperature : str
        'wellhead' or 'feedzone', see results.py.

    Returns
    -------
    str
        The path written.

    Raises
    ------
    ValueError
        If the profile holds no usable timestep.
    """
    rows = profile.temperature_profile_rows(profile_temperature)
    if not rows:
        raise ValueError(
            'The profile contains no successful timestep, so there is '
            'no temperature history to write. Check profile.notes for '
            'the reason.')

    lines = [f'# time [yr], {profile_temperature} temperature [C]',
             '# generated by the superhot-wellbore GEOPHIRES client']
    for time_yr, temperature_C in rows:
        lines.append(f'{time_yr:.6f},{temperature_C:.4f}')

    _write_lines(path, lines)
    return path


# ====================================================================
# INPUT DECK
# ====================================================================

def geophires_input_text(profile, reservoir_output_file,
                         profile_temperature='wellhead', extra=None):
    """
    Build the text of a GEOPHIRES input deck fragment.

    Parameters
    ----------
    profile : ProductionProfile
        Result of SuperhotWellboreClient.solve_profile().
    reservoir_output_file : str
        Value for 'Reservoir Output File Name'. GEOPHIRES resolves it
        relative to its own working directory, so a bare file name
        works when the deck and the profile sit side by side.
    profile_temperature : str
        Must match the value used for the profile file.
    extra : dict or None
        Additional 'Parameter Name' -> value entries.

    Returns
    -------
    str
        Deck text, ending with a newline.
    """
    if profile_temperature not in PROFILE_TEMPERATURES:
        raise ValueError(f'Unknown profile_temperature '
                         f'{profile_temperature!r}')

    parameters = profile.to_geophires_parameters(
        profile_temperature=profile_temperature, extra=extra)
    parameters['Reservoir Output File Name'] = reservoir_output_file

    summary = profile.summary()
    name = summary.get('name') or 'superhot'

    lines = [
        '# ==================================================='
        '=================',
        f'# GEOPHIRES input parameters for the superhot well '
        f'"{name}"',
        '# Generated by the superhot-wellbore GEOPHIRES client '
        '(superhot_wellbore.client).',
        '#',
        f'# The temperature profile in {reservoir_output_file} holds '
        f'the',
        f'# {profile_temperature} temperature computed by the coupled '
        f'reservoir-wellbore',
        '# model of Ingason-style superhot wells, re-solved along the '
        'declining',
        '# reservoir state described in the accompanying JSON result.',
        '#',
    ]

    for key, value in summary.items():
        if value is not None:
            lines.append(f'#   {key}: {_format_value(value)}')
    if profile.notes:
        lines.append('#')
        for note in profile.notes:
            lines.append(f'#   note: {note}')
    lines.append(
        '# ==================================================='
        '=================')
    lines.append('')

    written = set()
    for key in _PARAMETER_ORDER:
        if key in parameters:
            lines.append(_parameter_line(key, parameters[key]))
            written.add(key)
    for key in sorted(set(parameters) - written):
        lines.append(_parameter_line(key, parameters[key]))

    lines.extend([
        '',
        '-- Surface plant and economic parameters are outside the '
        'scope of the',
        '-- superhot-wellbore model. Add the ones your study needs '
        '(end-use',
        '-- option, power plant type, economic model, capital costs, '
        '...) below,',
        '-- or append this fragment to an existing deck.',
    ])

    return '\n'.join(lines) + '\n'


def _parameter_line(key, value):
    """Render one 'Name, value, comment' deck line."""
    comment = _PARAMETER_COMMENTS.get(key)
    rendered = _format_value(value)
    if comment:
        return f'{key}, {rendered}, {comment}'
    return f'{key}, {rendered}'


def write_geophires_input(profile, path, reservoir_output_file,
                          profile_temperature='wellhead', extra=None):
    """
    Write a GEOPHIRES input deck fragment. Returns the path written.
    """
    text = geophires_input_text(
        profile, reservoir_output_file,
        profile_temperature=profile_temperature, extra=extra)
    _write_lines(path, text.splitlines())
    return path


# ====================================================================
# FULL RESULT
# ====================================================================

def write_profile_json(profile, path):
    """Write the complete client result as JSON. Returns the path."""
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(profile.to_dict(), handle, indent=2)
        handle.write('\n')
    return path


def write_request_json(request, path):
    """Write a request as JSON. Returns the path."""
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(request.to_dict(), handle, indent=2)
        handle.write('\n')
    return path


# ====================================================================
# ALL AT ONCE
# ====================================================================

def export_all(profile, output_directory, name=None,
               profile_temperature='wellhead', extra=None):
    """
    Write the profile, the input deck and the JSON result.

    Parameters
    ----------
    profile : ProductionProfile
        Result of SuperhotWellboreClient.solve_profile().
    output_directory : str
        Directory to write into; created if missing.
    name : str or None
        File name stem. Defaults to the request name.
    profile_temperature : str
        'wellhead' or 'feedzone', see results.py.
    extra : dict or None
        Additional GEOPHIRES parameters for the deck.

    Returns
    -------
    dict
        Keys 'temperature_profile', 'geophires_input' and
        'profile_json', each holding the path written.
    """
    stem = name or getattr(profile.request, 'name', None) or 'superhot'
    os.makedirs(output_directory, exist_ok=True)

    profile_name = f'{stem}_reservoir_temperature.csv'
    paths = {
        'temperature_profile': write_temperature_profile(
            profile, os.path.join(output_directory, profile_name),
            profile_temperature=profile_temperature),
        'geophires_input': write_geophires_input(
            profile,
            os.path.join(output_directory, f'{stem}_geophires.txt'),
            reservoir_output_file=profile_name,
            profile_temperature=profile_temperature, extra=extra),
        'profile_json': write_profile_json(
            profile,
            os.path.join(output_directory, f'{stem}_profile.json')),
    }
    return paths


# ====================================================================
# INTERNAL
# ====================================================================

def _write_lines(path, lines):
    """Write lines to path, creating the parent directory if needed."""
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines) + '\n')
